---
# Ruby
- name: get currently installed ruby version
  command: ruby -v
  register: result
  ignore_errors: True

- name: Install ruby dependencies
  yum: name={{ item }}
       state=installed
  with_items:
    - gcc-c++
    - make
    - patch
    - readline
    - bzip2
    - autoconf 
    - automake 
    - libtool 
    - bison 
    - zlib
    - readline-devel
    - openssl-devel
    - libyaml-devel
    - zlib-devel
    - curl-devel
    - gettext-devel
    - libffi-devel
    - nodejs
when: result.rc !=0 or result.stdout.split()[1] != ruby.version

- name: Download binary from ruby offical website
  get_url: url={{ ruby.url }}
           dest={{ ruby.src_path }}
           sha256sum={{ ruby.sha256sum }}
  when: result.rc !=0 or result.stdout.split()[1] != ruby.version

- name: Uncompress...
  command: tar -xf {{ ruby.file }}
           chdir={{ ruby.src_path }}
  when: result.rc !=0 or result.stdout.split()[1] != ruby.version

- name: Install...
  command: name={{ item }}
           chdir="{{ ruby.src_path }}{{ ruby.dir }}"
  with_items:
    - ./configure
    - make
    - make install
  when: result.rc !=0 or result.stdout.split()[1] != ruby.version

- name: Install bundler
  command: gem install bundler

- name: Make Ruby symlinks
  file: path=/usr/bin/{{ item }}
        src=/usr/local/bin/{{ item }}
        state=link
  with_items:
    - gem
    - ruby
    - bundle

- name: Copy .gemrc to $HOME
  copy: src=gemrc
        dest={{ home }}/.gemrc
        backup=no