---
# Ruby
- name: Install ruby dependencies
  yum: name={{ item }}
       state=installed
  with_items:
    - gcc-c++
    - make
    - patch
    - readline
    - bzip2
    - autoconf 
    - automake 
    - libtool 
    - bison 
    - zlib
    - readline-devel
    - openssl-devel
    - libyaml-devel
    - zlib-devel
    - curl-devel
    - gettext-devel
    - libffi-devel
    - nodejs

- name: Download binary from ruby offical website
  get_url: url={{ ruby.url }}
           dest={{ ruby.src_path }}

- name: Uncompress...
  command: tar -xf {{ ruby.file }}
           chdir={{ ruby.src_path }}

- name: Configure...
  command: ./configure 
           chdir="{{ ruby.src_path }}{{ ruby.dir }}"

- name: Compiling...
  command: make 
           chdir="{{ ruby.src_path }}{{ ruby.dir }}"

- name: Installing...
  command: make install 
           chdir="{{ ruby.src_path }}{{ ruby.dir }}"

- name: Install bundler
  command: gem install bundler

- name: Make Ruby symlinks
  file: path=/usr/bin/{{ item }}
        src=/usr/local/bin/{{ item }}
        state=link
  with_items:
    - gem
    - ruby
    - bundle
    - node

- name: Copy .gemrc to $HOME
  copy: src=gemrc
        dest={{ home }}/.gemrc
        backup=no