---
- name: Copy nginx.repo
  copy: src=Nginx.repo
        dest=/etc/yum.repos.d/Nginx.repo
        owner=root
        group=root
        backup=yes

- name: Install nginx
  yum: name=nginx 
       state=present

#- name: Copy nginx configuration for wordpress
#  template: src=default.conf dest=/etc/nginx/conf.d/default.conf
#  notify: restart nginx
